//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkalTrucking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Card_ { get; set; }
        public string Driver_ { get; set; }
        public string Unit_ { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string T_S_ { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string ST { get; set; }
        public string Diesel_Gal { get; set; }
        public string Diesel_Amt { get; set; }
        public string Reefer_Gal { get; set; }
        public string Reefer_Amt { get; set; }
        public string Discnt { get; set; }
        public string Net_P_G { get; set; }
        public string Rebate { get; set; }
        public string Cash { get; set; }
        public string Other { get; set; }
        public string Invoice_Tot { get; set; }
    }
}
