//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkalTrucking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int Id { get; set; }
        public double Load_Number { get; set; }
        public string Reference_Number { get; set; }
        public System.DateTime First_Pickup { get; set; }
        public string P_U_Name { get; set; }
        public string P_U_City { get; set; }
        public string P_U_State_Prov { get; set; }
        public System.DateTime Last_Drop_off { get; set; }
        public string D_O_Name { get; set; }
        public string D_O_City { get; set; }
        public string D_O_State_Prov { get; set; }
        public string Status { get; set; }
        public double Trailer_Number { get; set; }
        public double Rate { get; set; }
    }
}
